# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Angular 2 Redux-like Todo App
email: gossekevin1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  angular 2 todo app by kevin gosse (gossekevin1@gmail.com)
baseurl: "https://kgosse.github.io/ngrx-store-todoapp" # the subpath of your site, e.g. /blog
url: "https://kgosse.github.io/ngrx-store-todoapp" # the base hostname & protocol for your site
twitter_username: kevingosse10
github_username:  kgosse

# Build settings
markdown: kramdown
